name: Generate a build and push to another branch

on:
  workflow_dispatch:
  push:
    branches:
      - lord

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: git-checkout
        uses: actions/checkout@v2

      - name: Add SHORT_SHA env property with commit short sha
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

      - name: That is not me, this is a bot
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Build
        run: python build/builder.py

      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build-stable
          FOLDER: styles
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Build styles: ({sha}) {msg}"
          SKIP_EMPTY_COMMITS: true

      - name: Commit new styles
        continue-on-error: true
        run: git diff-index --quiet HEAD || (git add --ignore-errors styles/* && git commit -m '[action for ${SHORT_SHA}] build styles' && git push -f)

      - name: Update readme
        run: python update-readme.py

      - name: Commit new readme if it was changed
        continue-on-error: true
        run: git diff-index --quiet HEAD || (git add --ignore-errors readme.md && git commit -m '[action for ${SHORT_SHA}] update readme' && git push -f)
