name: Generate a build and push to another branch

on:
  push:
    branches:
      - lord

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: git-checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Build
        run: python build/builder.py

      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build-stable
          FOLDER: styles
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Build styles: ({sha}) {msg}"

      - name: Update readme
        run: python update-readme.py

      - name: Commit new readme if it was changed
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git diff-index --quiet HEAD || (git add readme.md && git commit -m '[bot] update readme' && git push -f)
